### ISSUE TITLE
Add Zero to the roster

### ISSUE THREAD

**Issue by ARKEOLOGIST** [BurkusCat/r6-operator-counters#183] opened 2020-10-01 13:54 UTC
Zero has been a part of Rainbow Six for quite some time now. Isn't it time to add him to the list of operators?

**Comment by BurkusCat** [comment] 2020-10-01 18:53
Thanks for reporting the issue @ARKEOLOGIST . This is a duplicate of #175 so I am going to close.

**Closed by BurkusCat** 2020-10-01 18:53 UTC
Labels: good first issue
